import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
import Mygloballoader from "./Mygloballoader.js";
import { AuthProvider } from "./auth/context/AuthContext.js";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
          rel="stylesheet"
        />
      </head>
      <body>
        <AuthProvider>
          {children}
          <Mygloballoader />
        </AuthProvider>
      </body>
    </html>
  );
}
